
version: "2"

services:
  react-docker-pipeline:
    stdin_open: true
    build:
      context: .
    image: phumutta/react-docker-pipeline

    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    container_name: react-covid